### ISSUE TITLE
Remove es6-polyfills from dependencies

### ISSUE THREAD

**Issue by neverendingqs** [NatLibFi/loglevel-message-prefix#19]
`es6-polyfills` is licensed under `GPL-3.0`, which is a viral license.

> Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, **under the same license. Copyright and license notices must be preserved.** Contributors provide an express grant of patent rights.
> ~https://choosealicense.com/licenses/gpl-3.0/

Either this library should stop relying on `es6-polyfills`, or it should be licensed under `GPL-3.0` (and not under `MIT`).

**Comment by ghost** [comment]
Hello,

You are correct. I have misunderstood the copyleft virality.

Since we are also authors of `es-polyfills` I will relicense it under the [apache-2.0](https://choosealicense.com/licenses/apache-2.0) license.

**Comment by neverendingqs** [comment]
Thanks!

I think you need permission from all contributors to do that (but it looks like you're the only one, so that should be okay =) (IANAL).

**Comment by ghost** [comment]
I just released a new version which uses [es6-polyfills](https://github.com/natlibfi/es6-polyfills) version **2.0.0**, which is licensed under LGPL 3+
