### ISSUE TITLE
Add option to  define prefix and message separator

### ISSUE THREAD

**Issue by ghost** [NatLibFi/loglevel-message-prefix#7]
_As requested by @david-zacharias in #6._
# Description

Add an option to define a string that joins the prefix and the message.
# Implementation
1. Update schema
2. Implement in code

**Comment by david-zacharias** [comment]
It is already implemented in the pull request, including a test.

**Comment by ghost** [comment]
See my comments in #6. I prefer JSON configuration over JS code, if reasonable.

**Comment by ghost** [comment]
Elaborating on my previous comment: The configuration is validated against a schema and JSON schema [does not support functions](http://json-schema.org/latest/json-schema-core.html#anchor8).

**Comment by david-zacharias** [comment]
Sorry for questioning, but regarding preference of

> JSON configuration over JS code, if reasonable

you may could review the approach for this project, and leave out the schemas, based on following thoughts:

a) Schemas are used in this project to validate configuration done by developers at build time. Developers should now (by reading README or code) what a parameters are available and how to use them. Also, the interpreter will throw errors if parameters are misused I would opt for schemas if input is user- or machine-generated at runtime.

b) `jjv` and `jjve` attach 1000+ lines of dependencies to this loglevel plugin. Log level it self says it is 

> Minimal lightweight 

so plugins may join in this philosophy.

**Comment by ghost** [comment]
**a)** I disagree. A program may be use loglevel (With this plugin) internally, but it might be beneficial to allow users decide how the logs look like. This of course depends on the software but I think it's a neat feature and also removes the need to validate the configuration specific to this plugin separately since it's already done in the code.

Also, the reason why I used JSON schema in the first place was the versatile selection of validation constraints. If functionless configuration is sufficient, this removes the need to write custom validation rules in the code.

**b)** When I first selected loglevel as my JS choice of logging library, I was looking for a logger that would work in all environments, regardless of whether `console` was supported or not. At the time loglevel was the only mature project I could find. While loglevel indeed looks lightweight it's not the only reason people use it.

However, I will look into [optional minification of the code](https://github.com/NatLibFi/loglevel-message-prefix/issues/10).
